export default (
    Iconsrc = {
        icon_close_o: require("./../assets/mainicon/icon_close_o.png"),
        icon_user: require("./../assets/mainicon/icon_user.png"),
        icon_menu: require("./../assets/mainicon/icon_menu.png"),
        topimguri: require("./../assets/cityinntopimage.jpg"),
        calendericon: require("./../assets/Icon/Calendar.png"),
        logoicon: require("./../assets/mainicon/mainlogo.png"),
        cloudicon: require("./../assets/Icon/icon-w-cloud.png"),
        digitalkey:require("./../assets/mainicon/doorLock.png"),
        wifi:require("./../assets/mainicon/wifi_icon.png"),
        elevator:require("./../assets/mainicon/lift.png"),
        room:require("./../assets/mainicon/cusCon.png"),
        degreeicon:require("./../assets/mainicon/icon_720.png"),
        gym:require("./../assets/mainicon/gym.png"),
        swimmimg:require("./../assets/mainicon/icon-swimmingsool.png"),
        home:require("./../assets/Icon/home.jpg"),
        ballicon:require("./../assets/mainicon/icon_foot_1pre.png"),
        ballicongrey:require("./../assets/mainicon/icon_foot_1.png"),
        footer2:require("./../assets/mainicon/icon_foot_2pre.png"),
        footer2grey:require("./../assets/mainicon/icon_foot_2.png"),
        footer3:require("./../assets/mainicon/icon_foot_3pre.png"),
        footer3grey:require("./../assets/mainicon/icon_foot_3.png"),
        footer4:require("./../assets/mainicon/icon_foot_4pre.png"),
        footer4grey:require("./../assets/mainicon/icon_foot_4.png"),
        redar:require("./../assets/Icon/radar-L.png"),
        msg:require("./../assets/mainicon/icon_message.png"),
        logout:require("./../assets/mainicon/icon_loginout.png"),
        pwd:require("./../assets/mainicon/pwd.png"),
        viewOrder:require("./../assets/mainicon/viewOrder.png"),
        icon_right:require("./../assets/mainicon/icon_right.png"),
        numbericon:require("./../assets/mainicon/icon_number.png"),
        personicon:require("./../assets/mainicon/icon_person.png"),
        fireplan:require("./../assets/Icon/ascott-heng-shan-shanghai-3-bedroom-deluxe-floor-plan.png"),
        bus:require("./../assets/mainicon/icon-bus.png"),
        unlock:require("./../assets/Icon/unlock.png"),
        arrow:require("./../assets/Icon/arrow.png"),
        dot:require("./../assets/Icon/dot.png"),
        icback:require("./../assets/Icon/ic_back.jpg"),
        sleepinggray:require("./../assets/Icon/Calendar.png"),
        sleeping:require("./../assets/Yellow/lifestyle.png"),
        teal:require("./../assets/Icon/teaL.png"),
    }
)